version: "3"
services:
  student:
    container_name: student-con
    build: .
    ports:
      - "7070:7070"
    environment:
      - PORTS=7070
      - PHASE_TYPE=PRO
    env_file:
      - ./.env


