version: "3"
services:
  docker-demo:
    build:
       context: .
       target: development
    volumes:
      - .:/docker-demo:ro
    ports:
      - "9090:9090"
    environment:
      - PORTS=9090
      - PHASE_TYPE=DEV


